### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by guzhongren** [Chorss/docker-pgAdmin4#15]
```yml
image: chorss/docker-pgadmin4
    ports:
      - 8888:5050
    environment:
      - SERVER_MODE=true
      - PGADMIN_SETUP_EMAIL=xxxxxx@lxx.cn
      - PGADMIN_SETUP_PASSWORD=xxxxxx
    volumes:
      - ./pgadmin_data:/data 
```

this is my docker-compose.yml file, i start stack ,in browser i can open web page,but i input xxxxxx@lxx.cn / xxxxxx, login failed... what' wrong , your doc less of something ,,you know

**Comment by Chorss** [comment]
Hi,

asd

> version: '3'

services:
  postgres:
    container_name: postgres
    restart: always #Autostart
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_PASSWORD=postgres

  pgadmin4:
    container_name: pgadmin4
    #restart: always #Autostart
    image: chorss/docker-pgadmin4
    volumes:
      - /home/chorss/programming/pgAdmin4:/data
    links:
      - postgres
    ports:
      - 8888:5050
    environment:
      - SERVER_MODE=true
      - PGADMIN_SETUP_EMAIL=xxxxxx@lxx.cn
      - PGADMIN_SETUP_PASSWORD=xxxxxx

**Comment by Chorss** [comment]
Hi,

Login works. I tested on my docker-compose.yml

```yml
version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - DEBUG=false
      - POSTGRES_PASSWORD=postgres

  pgadmin4:
    container_name: pgadmin4
    image: chorss/docker-pgadmin4
    volumes:
      - ./pgadmin_data:/data 
    links:
      - postgres
    ports:
      - 8888:5050
    environment:
      - SERVER_MODE=true
      - PGADMIN_SETUP_EMAIL=xxxxxx@lxx.cn
      - PGADMIN_SETUP_PASSWORD=xxxxxx
```
